### ISSUE TITLE
可以提供一个测试账号吗?

### ISSUE THREAD

**Issue by Woxiee** [GuardianFirewall/GuardianConnect#15]
您好,可以提供一个测试登录的账号吗

**Comment by tzeejay** [comment]
@Woxiee Hey we can't provide you with a test account since most of the authentication is currently based on Apple's IAP system. You would have to provide us with your IAP shared secret
I also noticed that you are writing in Chinese and due to laws imposed by the Chinese Government you wont be able to connect to our nodes since the underlying connection relies on a VPN implementation

**Comment by Woxiee** [comment]
> @Woxiee Hey we can't provide you with a test account since most of the authentication is currently based on Apple's IAP system. You would have to provide us with your IAP shared secret
> I also noticed that you are writing in Chinese and due to laws imposed by the Chinese Government you wont be able to connect to our nodes since the underlying connection relies on a VPN implementation

THX
